version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=booker
      - POSTGRES_PASSWORD=booker

  server:
    build: C:/Users/demon/dev/java-shareit/server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=booker
      - POSTGRES_PASSWORD=booker

  gateway:
    build: C:/Users/demon/dev/java-shareit/gateway
    container_name: shareit-web
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

